spring:
  application:
    name: { APPLICATION_NAME:product-project-manager }
    initial: PPM
  codec:
    max-in-memory-size: 100MB
  data:
    web:
      pageable:
        max-page-size: 1000000
  datasource:
    url: { POSTGRESDB_URI:jdbc:postgresql://localhost:5432/postgres }
    username: { POSTGRESDB_USER:postgres }
    password: { POSTGRESDB_PASSWORD:example }
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lab:
              '[non_contextual_creation]': true
          validator:
            '[apply_to_ddl]': false